request_header_user_agent: nfdi4dsBot/1.0 (https://www.nfdi4datascience.de/nfdi4dsBot/; nfdi4dsBot@nfdi4datascience.de)
search_url_resodate: https://resodate.org/resources/api/search/oer_data/_search?pretty&size=100&q=
