services:
    search-engine:
        build: .
        ports:
            - 6000:5002
        restart: unless-stopped
        networks:
            - demo_network
networks:
    demo_network:
        external: true
