services:
    search-engine:
        build: .
        ports:
            - 6000:5002
        restart: unless-stopped
networks:
    search-engine-network:
        name: search-engine-network
        external: true
