services:
    search-engine:
        build: .
        ports:
            - 6000:5002
        restart: unless-stopped
        networks:
            - search_engine_network
networks:
    search_engine_network:
        external: true
