name: 'Deploy NFDI Search Engine on sems-kg-1'
on:
  workflow_dispatch:
  push:
    branches: 
      - main
  release:
    types: [published]

jobs:
  deploy:
    runs-on: sems-kg-1
    steps:
      - name: 'Check out repo'
        uses: actions/checkout@v3
      - name: 'Write dummy file for debugging'
        run: 'echo "Works" >> /tmp/gh_action_was_here.txt'
        
