name: 'Deploy NFDI Search Engine on sems-kg-1'
on:
  workflow_dispatch:
  push:
    branches: 
      - main

jobs:
  deploy:
    runs-on: [self-hosted, sems-kg-1]    
    steps:
      - name: 'Check out repo'
        uses: actions/checkout@v3
        with:
          ref: main
      - name: 'Stop the running NFDI Search Engine'
        run: docker compose down
      - name: 'Delete old Docker image'
        run: docker image rm nfdi-search-engine-search-engine || (echo "Image nfdi-search-engine-search-engine didn't exist so not removed."; exit 0)
      - name: 'Copy logging.conf'
        run: cp logging.conf.example logging.conf       
      - name: 'Create .env'
        run: |
          echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> ./.env
          echo "IEEE_API_KEY=${{ secrets.IEEE_API_KEY }}" >> ./.env
          echo "CLIENT_ID_GOOGLE=${{ secrets.CLIENT_ID_GOOGLE }}" >> ./.env
          echo "CLIENT_SECRET_GOOGLE=${{ secrets.CLIENT_SECRET_GOOGLE }}" >> ./.env
          echo "CLIENT_ID_GITHUB=${{ secrets.CLIENT_ID_GITHUB }}" >> ./.env
          echo "CLIENT_SECRET_GITHUB=${{ secrets.CLIENT_SECRET_GITHUB }}" >> ./.env
          echo "CLIENT_ID_ORCID=${{ secrets.CLIENT_ID_ORCID }}" >> ./.env
          echo "CLIENT_SECRET_ORCID=${{ secrets.CLIENT_SECRET_ORCID }}" >> ./.env
          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> ./.env
          echo "LLAMA3_USERNAME=${{ secrets.LLAMA3_USERNAME }}" >> ./.env
          echo "LLAMA3_PASSWORD=${{ secrets.LLAMA3_PASSWORD }}" >> ./.env
          echo "ELASTIC_SERVER=${{ secrets.ELASTIC_SERVER }}" >> ./.env
          echo "ELASTIC_USERNAME=${{ secrets.ELASTIC_USERNAME }}" >> ./.env
          echo "ELASTIC_PASSWORD=${{ secrets.ELASTIC_PASSWORD }}" >> ./.env
          echo "CHATBOT_SERVER=${{ secrets.CHATBOT_SERVER }}" >> ./.env
      - name: 'Re-build Docker container from current source'
        run: docker compose up --force-recreate --build --detach
